# Generated by Django 3.1.7 on 2021-03-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertismentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_images')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.advertisment')),
            ],
        ),
    ]
