# Generated by Django 3.1.7 on 2021-03-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0002_advertismentimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentimages',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_site.advertisment'),
        ),
    ]
