# Generated by Django 3.1.7 on 2021-03-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_auto_20210305_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='image',
        ),
        migrations.AddField(
            model_name='advertismentimages',
            name='description',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
